### ISSUE TITLE
dtx_phase2_retry_count parameter issue

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#176]
Page No : 1324

Issue: This parameter cannot set using gpconfig, able to set using psql.

Yes it's not given under the parameter list (gpconfig -l), It's better to have a Note same here.

[gpadmin@mdw_ipv4 pg_log]$ gpconfig -c dtx_phase2_retry_count -v 15
20210713:18:08:08:032385 gpconfig:mdw_ipv4:gpadmin-[CRITICAL]:-GUC Validation Failed: dtx_phase2_retry_count cannot be changed under normal conditions. Please refer to gpconfig documentation.
GUC Validation Failed: dtx_phase2_retry_count cannot be changed under normal conditions. Please refer to gpconfig documentation.
[gpadmin@mdw_ipv4 pg_log]$

**Comment by edespino** [comment]
@ashwinstar The following commit introduces the `dtx_phase2_retry_count` parameter. It cannot be set by gpconfig. It is not clear if this is a mistake or only used during testing (which it is). Any ideas?

git log --grep="Refactor distributed"
commit c6320c132e8a9ff0bdb77053048867c61dfc5471
Author: Asim R P <apraveen@pivotal.io>
Date:   Mon Oct 24 16:50:05 2016 -0700

Refactor distributed transaction phase 2 retry logic.

Refactor the phase 2 retry logic of distributed transaction so that the retry happens
immediately after failure instead of happening inside EndCommand(). The patch also
increases the number of retries in case of failure to 2 and introduces a guc called
dtx_phase2_retry_count to control the number of retries.

**Comment by ashwinstar** [comment]
The guc is marked as `DEVELOPER_OPTIONS` and hence that's the behavior. Ideally, using `--skipvalidation` gpconfig flag should be able to set the GUC. I don't see why we can't expose this guc to customers. So, wish can open PR to fix it and make it visible.
