### ISSUE TITLE
Hyperlink in latest Greenplum Database document points to older PXF document

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#234]
Location: https://gpdb.docs.pivotal.io/6-18/admin_guide/external/pxf-overview.html

The Greenplum Database document has a topic **Working with External Data** > **Accessing External Data with PXF**
The section says 
"For detailed information about the architecture of and using PXF, refer to the **Greenplum Platform Extension Framework (PXF)** documentation."

Clicking on the above link takes the user to the PXF documentation page at https://gpdb.docs.pivotal.io/pxf/5-15/using/overview_pxf.html with version 5.15 selected. This should ideally take the user to the latest version of the PXF document (v6.18)

**Comment by lisakowen** [comment]
this is by design.  the version of pxf that is currently bundled with the greenplum 6.x distribution is 5.15.1.  because of this, the greenplum docs link to the 5.15.1 of the pxf docs.  in the near future, we will remove bundled pxf from the greenplum server package.  when we do this, the links will be updated to pxf/latest/.
