### ISSUE TITLE
Incorrect description for "gpcheckcat -O"

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#58]
Page No : 242

1) -O option is for online tests, this runs only 10 out of 15 tests.
2) And this can be run while the DB is up and running. 

It will be good if these points are mentioned in Activity.

- Given Command
Run the Greenplum gpcheckcat
utility in each database:
gpcheckcat -O

**Comment by VMWareJennyBeth** [comment]
@bala-cg 

If I say it's it runs just 10 out of the 15 tests, I probably want to tell them which tests it does NOT cover. Do you know what they are? Is that worth mentioning?

**Comment by VMWareJennyBeth** [comment]
Docs issue created.

**Comment by VMWareJennyBeth** [comment]
@bala-cg 

Hi, Bala! I reopened this because I realized I'm still not confident of what you're asking for here. 

I know that you want the Activity box to state that this command / flag:

1. Should be run in each database
2. Can be run while the database is up and running

I'm not sure what else you'd like me to mention

**Comment by bala-cg** [comment]
Hi Jeeny,

- gpcheckcat will usually run 15 tests, and it need to be run in restricted mode, with "-O" online option it runs only 10 tests out of 15.
- There's no mention "gpcheckcat -O" will only run 10 tests out of 15, and this test can be run while DB is open for normal operations.

**Comment by VMWareJennyBeth** [comment]
@bala-cg 
Thank you!

**Comment by VMWareJennyBeth** [comment]
Docs story created.
